source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby ">= 3.1.0"

gem "rails", "~> 7.1.3"
# mysql2 for local development (matches your existing local MySQL setup);
# pg for the production database on Render, which offers free managed
# Postgres but not MySQL. Both gems are lightweight to have installed.
gem "mysql2", "~> 0.5"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.7"
gem "rack-cors"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end
